resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: quay.io/jmoller/lvms-operator
  newTag: latest
namePrefix: lvms-
namespace: openshift-storage
