kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubesan-csi-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubesan-csi-controller
subjects:
  - kind: ServiceAccount
    name: kubesan-csi-controller-plugin
    namespace: system
