kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: blobs
rules:
  - apiGroups: [""]
    resources: [persistentvolumes]
    verbs: [get, update]
  - apiGroups: [""]
    resources: [services]
    verbs: [create, delete]
  - apiGroups: [apps]
    resources: [replicasets]
    verbs: [create, delete, get]
  - apiGroups: [batch]
    resources: [jobs]
    verbs: [create, delete, get]
  - apiGroups: [storage.k8s.io]
    resources: [storageclasses]
    verbs: [get, update]
  - apiGroups: [kubesan.gitlab.io]
    resources: [blobpools]
    verbs: [create, delete, get, update]
