kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubesan-blobs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubesan-blobs
subjects:
  - kind: ServiceAccount
    name: kubesan-csi-controller-plugin
    namespace: system
  - kind: ServiceAccount
    name: kubesan-csi-node-plugin
    namespace: system
  - kind: ServiceAccount
    name: vg-manager
    namespace: system
