kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubesan-csi-controller
rules:
  - apiGroups: [""]
    resources: [persistentvolumeclaims]
    verbs: [get]
  - apiGroups: [batch]
    resources: [jobs]
    verbs: [create, delete, get]
