#!/bin/bash
supported_versions=("v4.14" "v4.15" "v4.16" "v4.17" "v4.18" "v4.19" "v4.20")
bundle_path="registry.redhat.io/lvms4/lvms-operator-bundle"
pre_release_bundle_path="registry.stage.redhat.io/lvms4/lvms-operator-bundle"
lvms_all_tags="$(skopeo list-tags docker://${pre_release_bundle_path})"
lvms_released_tags="$(skopeo list-tags docker://${bundle_path})"
all_versions=($(echo "${lvms_all_tags}" | yq '[.Tags[] | select(test("^v[[:digit:]]+\.[[:digit:]]+$"))] | join(" ")'))
verbose_versions=$(echo "${lvms_all_tags}" | yq '[.Tags[] | select(test("^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$"))]')
released_versions=$(echo "${lvms_released_tags}" | yq '[.Tags[] | select(test("^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$"))] | join(" ")')
base_template_file="templates/template-base.yaml"
template=$(yq '.Stable.Bundles = []' ${base_template_file})

declare -A digests

for i in "${!released_versions[@]}"; do
    maxVersion=""
    minVersion="${all_versions[${i}]}"

    if [ "${i}" -lt ${#all_versions[@]} ] && [ "${i}" -gt 0 ]; then
        maxVersion="${all_versions[${i}-1]}"
    else
        maxVersion="${released_versions[${i}]}"
    fi

    if ! [[ " ${supported_versions[*]} " =~ " ${minVersion} " ]]; then
        echo "Skipping ${minVersion} since it is no longer supported"
        continue
    fi

    echo "Generating catalog template for LVM Operator ${minVersion}"

    catalog_versions=($(echo "${verbose_versions}" | yq "[.[] | select(contains(\"${maxVersion}\") or contains(\"${minVersion}\"))] | join(\" \")"))

    catalog_template="# WARNING THIS FILE IS AUTOGENERATED - DO NOT EDIT\n${template}"
    for ver in "${catalog_versions[@]}"; do
        version="${ver//./}"
        if ! [[ -n "${digests["${ver}"]}" ]]; then
            digests["${ver}"]=$(skopeo inspect "docker://${bundle_path}:${ver}" --format "{{.Digest}}")
            echo "Pinning ${ver} to ${digests["${ver}"]}"
        fi

        catalog_template=$(echo "${catalog_template}" | yq ".Stable.Bundles += {\"Image\": \"${bundle_path}@${digests["${ver}"]}\"}")
    done

    echo -e "${catalog_template}" > "templates/lvm-operator-catalog-${minVersion}-template.yaml"
done
