#!/bin/bash
bundle_path="registry.redhat.io/lvms4/lvms-operator-bundle"
lvms_released_tags="$(skopeo list-tags docker://${bundle_path})"
released_versions=($(echo "${lvms_released_tags}" | yq '[.Tags[] | select(test("^v[[:digit:]]+\.[[:digit:]]+$"))] | join(" ")'))
verbose_versions=$(echo "${lvms_released_tags}" | yq '[.Tags[] | select(test("^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$"))]')
base_template_file="templates/template-base.yaml"
template=$(yq '.Stable.Bundles = []' ${base_template_file})

for i in "${!released_versions[@]}"; do
    maxVersion=""
    minVersion="${released_versions[${i}]}"

    if [ "${i}" -lt ${#released_versions[@]} ] && [ "${i}" -gt 0 ]; then
        maxVersion="${released_versions[${i}-1]}"
    else
        maxVersion="${released_versions[${i}]}"
    fi

    echo "Generating catalog template for LVM Operator ${minVersion}"

    catalog_versions=($(echo "${verbose_versions}" | yq "[.[] | select(contains(\"${maxVersion}\") or contains(\"${minVersion}\"))] | join(\" \")"))

    catalog_template="# WARNING THIS FILE IS AUTOGENERATED - DO NOT EDIT\n${template}"
    for ver in ${catalog_versions[@]}; do
        catalog_template=$(echo "${catalog_template}" | yq ".Stable.Bundles += {\"Image\": \"${bundle_path}:${ver}\"}")
    done

    echo -e "${catalog_template}" > "templates/lvm-operator-catalog-${minVersion}-template.yaml"
done
