apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: kubesan-enablement-layer
spec:
  osImageURL: quay.io/bzamalut/node-base-kubesan-patched:v4.17.0-00
