// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package lvmd

import (
	"context"

	"github.com/openshift/lvm-operator/v4/internal/controllers/vgmanager/lvmd"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfigurator creates a new instance of MockConfigurator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigurator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigurator {
	mock := &MockConfigurator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigurator is an autogenerated mock type for the Configurator type
type MockConfigurator struct {
	mock.Mock
}

type MockConfigurator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigurator) EXPECT() *MockConfigurator_Expecter {
	return &MockConfigurator_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockConfigurator
func (_mock *MockConfigurator) Delete(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfigurator_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockConfigurator_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConfigurator_Expecter) Delete(ctx interface{}) *MockConfigurator_Delete_Call {
	return &MockConfigurator_Delete_Call{Call: _e.mock.On("Delete", ctx)}
}

func (_c *MockConfigurator_Delete_Call) Run(run func(ctx context.Context)) *MockConfigurator_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurator_Delete_Call) Return(err error) *MockConfigurator_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfigurator_Delete_Call) RunAndReturn(run func(ctx context.Context) error) *MockConfigurator_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type MockConfigurator
func (_mock *MockConfigurator) Load(ctx context.Context) (*lvmd.Config, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *lvmd.Config
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*lvmd.Config, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *lvmd.Config); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lvmd.Config)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConfigurator_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockConfigurator_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConfigurator_Expecter) Load(ctx interface{}) *MockConfigurator_Load_Call {
	return &MockConfigurator_Load_Call{Call: _e.mock.On("Load", ctx)}
}

func (_c *MockConfigurator_Load_Call) Run(run func(ctx context.Context)) *MockConfigurator_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurator_Load_Call) Return(v *lvmd.Config, err error) *MockConfigurator_Load_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockConfigurator_Load_Call) RunAndReturn(run func(ctx context.Context) (*lvmd.Config, error)) *MockConfigurator_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockConfigurator
func (_mock *MockConfigurator) Save(ctx context.Context, config *lvmd.Config) error {
	ret := _mock.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lvmd.Config) error); ok {
		r0 = returnFunc(ctx, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfigurator_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockConfigurator_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - config *lvmd.Config
func (_e *MockConfigurator_Expecter) Save(ctx interface{}, config interface{}) *MockConfigurator_Save_Call {
	return &MockConfigurator_Save_Call{Call: _e.mock.On("Save", ctx, config)}
}

func (_c *MockConfigurator_Save_Call) Run(run func(ctx context.Context, config *lvmd.Config)) *MockConfigurator_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *lvmd.Config
		if args[1] != nil {
			arg1 = args[1].(*lvmd.Config)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigurator_Save_Call) Return(err error) *MockConfigurator_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfigurator_Save_Call) RunAndReturn(run func(ctx context.Context, config *lvmd.Config) error) *MockConfigurator_Save_Call {
	_c.Call.Return(run)
	return _c
}
