---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: lvm-operator-catalog-4-14-20260608-074935-000
  namespace: logical-volume-manag-tenant
  labels:
    release.appstudio.openshift.io/author: "Pablo Acevedo Montserrat <pacevedo@redhat.com>"
spec:
  releasePlan: lvm-operator-catalog-production-releaseplan-4-14
  snapshot: lvm-operator-catalog-4-14-20260608-074935-000
