---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
    name: lvm-operator-rhba-v4.17.7
    namespace: logical-volume-manag-tenant
    labels:
        release.appstudio.openshift.io/author: "Kasturi Narra <knarra@redhat.com>"
spec:
    releasePlan: lvm-operator-production-releaseplan-4-17
    snapshot: lvm-operator-4-17-20260611-084943-000
    data:
        releaseNotes:
            description: |
                After a successful LVMS upgrade, the latest lvms-operator SHA image should be running.

                This erratum implements the following changes:

                - {!! TODO !!}

                Users of LVMS are advised to upgrade to the latest version in OpenShift Container Platform, which fixes these bugs and adds these enhancements.
