---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: lvm-operator-rhba-v4.20.1-1
  namespace: logical-volume-manag-tenant
  labels:
    release.appstudio.openshift.io/author: "Pablo Acevedo Montserrat <pacevedo@redhat.com>"
spec:
  releasePlan: lvm-operator-production-releaseplan-4-20
  snapshot: lvm-operator-4-20-1-manual-release
  data:
    releaseNotes:
      description: |
        After a successful LVMS upgrade, the latest lvms-operator SHA image should be running.

        This erratum implements the following changes:

        - Fixes leaked per-node wipe annotations on LVMVolumeGroup objects on node deletion
        - Bumps gRPC-Go to 1.79.3 to address CVE-2026-33186 authorization bypass vulnerability

        Users of LVMS are advised to upgrade to the latest version in OpenShift Container Platform, which fixes these bugs and adds these enhancements.
