---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: lvm-operator-catalog-4-16-11
  namespace: logical-volume-manag-tenant
  labels:
    release.appstudio.openshift.io/author: "Pablo Acevedo Montserrat <pacevedo@redhat.com>"
spec:
  releasePlan: lvm-operator-catalog-production-releaseplan-4-16
  snapshot: lvm-operator-catalog-4-16-20260605-034552-000
