# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/lvm.topolvm.io_lvmclusters.yaml
# Topolvm CRD from https://github.com/openshift/topolvm/blob/main/config/crd/bases/topolvm.io_logicalvolumes.yaml
- bases/topolvm.io_logicalvolumes.yaml
- bases/lvm.topolvm.io_lvmvolumegroups.yaml
- bases/lvm.topolvm.io_lvmvolumegroupnodestatuses.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
  # The following patch adds an additionalPrinterColumn called Status into the LVMCluster CRD.
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: lvmclusters.lvm.topolvm.io
    path: patches/additionalPrinterColumn_in_lvmcluster.yaml

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
