apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/lvm-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "catalog" &&
      (".tekton/catalog-pipeline.yaml".pathChanged() ||
      ".tekton/lvm-operator-catalog-v4.14-pull-request.yaml".pathChanged() ||
      ".tekton/lvm-operator-catalog-v4.14-push.yaml".pathChanged() ||
      "catalogs/lvm-operator-catalog-v4.14.json".pathChanged() ||
      "templates/lvm-operator-catalog-v4.14-template.yaml".pathChanged() ||
      "konflux-catalog.Dockerfile".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: lvm-operator-catalog
    appstudio.openshift.io/component: lvm-operator-catalog-v4-14
    pipelines.appstudio.openshift.io/type: build
  name: lvm-operator-catalog-v4.14-on-push
  namespace: logical-volume-manag-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/logical-volume-manag-tenant/lvm-operator-catalog:v4.14-{{revision}}
  - name: dockerfile
    value: konflux-catalog.Dockerfile
  - name: build-args
    value:
    - CATALOG_VERSION=v4.14
    - BASE_IMAGE=registry.redhat.io/openshift4/ose-operator-registry
  - name: hermetic
    value: "true"
  pipelineRef:
    resolver: bundles
    params:
      - name: name
        value: fbc-builder
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder:devel@sha256:4a6f4813d35303b0fd50dae2b2b7cf994ff43c4d81f38193ec01167ccfa0b6a2
      - name: kind
        value: pipeline
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
