#!/bin/bash

source gather_common
get_log_collection_args

# Expect base collection path as an argument
BASE_COLLECTION_PATH=$1

# Use PWD as base path if no argument is passed
if [ "${BASE_COLLECTION_PATH}" = "" ]; then
    BASE_COLLECTION_PATH=$(pwd)
fi

# There might be cases where the operator might be installed in a different namespace
# The INSTALL_NAMESPACE parameter does not account for old installations when it was running
# on project "openshift-storage" by default.
# This causes the must-gather to not collect data properly
# INSTALL_NAMESPACE=openshift-lvm-storage
# There might be different ways to sort the namespace installation namespace
#
#   We filter based on the CSV object for "lvms-operator"
#   oc get csv -A | grep lvms-operator | cut -f1 -d " "
#   Give a list of project where the operator is detected, example output:
#   ~~~
#   $ oc get csv -A | grep lvms-operator | cut -f1 -d " "
#   lvm-operator-for-everyone
#   openshift-storage
#   ~~~
# This will return an array of namespaces
mapfile -t INSTALL_NAMESPACE < <(oc get csv --all-namespaces | grep lvms-operator | cut -f1 -d " ")

# collection path for OC commands
mkdir -p "${BASE_COLLECTION_PATH}/oc_output/"

# Command List
commands_get=()

# collect oc output of OC get commands
commands_get+=("lvmcluster")
commands_get+=("lvmvolumegroup")
commands_get+=("lvmvolumegroupnodestatus")
commands_get+=("logicalvolume")
commands_get+=("pods -owide")
commands_get+=("subscription")
commands_get+=("csv")
commands_get+=("installplan")
commands_get+=("events")
commands_get+=("all -o wide")
commands_get+=("role")
commands_get+=("rolebinding")

# collect oc output of OC desc commands
commands_desc=()
commands_desc+=("lvmcluster")
commands_desc+=("logicalvolume")
commands_desc+=("lvmvolumegroup")
commands_desc+=("lvmvolumegroupnodestatus")
commands_desc+=("pods")

# collect yaml output of OC commands
oc_yamls=()
oc_yamls+=("csv")
oc_yamls+=("installplan")

echo "collecting dump of namespace" | tee -a "${BASE_COLLECTION_PATH}"/gather-debug.log

for NAMESPACE in "${INSTALL_NAMESPACE[@]}"; do
    oc adm --dest-dir="${BASE_COLLECTION_PATH}" inspect ns/"$NAMESPACE" ${log_collection_args} >>"${BASE_COLLECTION_PATH}"/gather-debug.log 2>&1
done

echo "collecting dump of clusterresourceversion" | tee -a "${BASE_COLLECTION_PATH}"/gather-debug.log
for NAMESPACE in "${INSTALL_NAMESPACE[@]}"; do
    for oc_yaml in "${oc_yamls[@]}"; do
        # shellcheck disable=SC2129
        oc adm --dest-dir="${BASE_COLLECTION_PATH}" inspect "${oc_yaml}" -n "$NAMESPACE" ${log_collection_args} >>"${BASE_COLLECTION_PATH}"/gather-debug.log 2>&1
    done
done

# Create the dir for oc_output
for NAMESPACE in "${INSTALL_NAMESPACE[@]}"; do
    mkdir -p "${BASE_COLLECTION_PATH}/namespaces/${NAMESPACE}/oc_output/"
done

# Run the Collection of OC get commands
for NAMESPACE in "${INSTALL_NAMESPACE[@]}"; do
    for command_get in "${commands_get[@]}"; do
        echo "collecting oc command ${command_get}" | tee -a "${BASE_COLLECTION_PATH}/gather-debug.log"
        COMMAND_OUTPUT_FILE=${BASE_COLLECTION_PATH}/namespaces/${NAMESPACE}/oc_output/${command_get// /_}
        # shellcheck disable=SC2086
        { oc get ${command_get} -n ${NAMESPACE}; } >>"${COMMAND_OUTPUT_FILE}"
    done
done

# Run the Collection of OC desc commands
for NAMESPACE in "${INSTALL_NAMESPACE[@]}"; do
    for command_desc in "${commands_desc[@]}"; do
    echo "collecting oc describe command ${command_desc}" | tee -a "${BASE_COLLECTION_PATH}/gather-debug.log"
    COMMAND_OUTPUT_FILE=${BASE_COLLECTION_PATH}/namespaces/${NAMESPACE}/oc_output/${command_desc// /_}
    # shellcheck disable=SC2086
    { oc describe ${command_desc} -n ${NAMESPACE}; } >>"${COMMAND_OUTPUT_FILE}"
    done
done

for NAMESPACE in "${INSTALL_NAMESPACE[@]}"; do
    { oc get lvmclusters -n ${NAMESPACE} -o yaml; } >"$BASE_COLLECTION_PATH/namespaces/${NAMESPACE}/oc_output/lvmcluster.yaml" 2>&1
done

# Create the dir for data from all namespaces
mkdir -p "${BASE_COLLECTION_PATH}/namespaces/all/"

# For pvc of all namespaces
echo "collecting dump of oc get pvc all namespaces" | tee -a "${BASE_COLLECTION_PATH}/gather-debug.log"
{ oc get pvc --all-namespaces; } >>"${BASE_COLLECTION_PATH}/namespaces/all/pvc_all_namespaces"
{ oc adm --dest-dir="${BASE_COLLECTION_PATH}/namespaces/all/" inspect pvc --all-namespaces ${log_collection_args}; } >>"${BASE_COLLECTION_PATH}/gather-debug.log" 2>&1

# For snapshot of all namespaces
echo "collecting dump of snapshot information for all namespaces" | tee -a "${BASE_COLLECTION_PATH}/gather-debug.log"
{ oc get volumesnapshot --all-namespaces; } >>"${BASE_COLLECTION_PATH}/namespaces/all/get_volumesnapshot_all_namespaces"
{ oc describe volumesnapshot --all-namespaces; } >>"${BASE_COLLECTION_PATH}/namespaces/all/desc_volumesnapshot_all_namespaces"
{ oc adm --dest-dir="${BASE_COLLECTION_PATH}/namespaces/all/" inspect volumesnapshot --all-namespaces ${log_collection_args}; } >>"${BASE_COLLECTION_PATH}/gather-debug.log" 2>&1
