// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package lvm

import (
	"context"

	"github.com/openshift/lvm-operator/v4/internal/controllers/vgmanager/lvm"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLVM creates a new instance of MockLVM. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLVM(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLVM {
	mock := &MockLVM{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLVM is an autogenerated mock type for the LVM type
type MockLVM struct {
	mock.Mock
}

type MockLVM_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLVM) EXPECT() *MockLVM_Expecter {
	return &MockLVM_Expecter{mock: &_m.Mock}
}

// ActivateLV provides a mock function for the type MockLVM
func (_mock *MockLVM) ActivateLV(ctx context.Context, lvName string, vgName string) error {
	ret := _mock.Called(ctx, lvName, vgName)

	if len(ret) == 0 {
		panic("no return value specified for ActivateLV")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, lvName, vgName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLVM_ActivateLV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActivateLV'
type MockLVM_ActivateLV_Call struct {
	*mock.Call
}

// ActivateLV is a helper method to define mock.On call
//   - ctx context.Context
//   - lvName string
//   - vgName string
func (_e *MockLVM_Expecter) ActivateLV(ctx interface{}, lvName interface{}, vgName interface{}) *MockLVM_ActivateLV_Call {
	return &MockLVM_ActivateLV_Call{Call: _e.mock.On("ActivateLV", ctx, lvName, vgName)}
}

func (_c *MockLVM_ActivateLV_Call) Run(run func(ctx context.Context, lvName string, vgName string)) *MockLVM_ActivateLV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLVM_ActivateLV_Call) Return(err error) *MockLVM_ActivateLV_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLVM_ActivateLV_Call) RunAndReturn(run func(ctx context.Context, lvName string, vgName string) error) *MockLVM_ActivateLV_Call {
	_c.Call.Return(run)
	return _c
}

// AddTagToVG provides a mock function for the type MockLVM
func (_mock *MockLVM) AddTagToVG(ctx context.Context, vgName string) error {
	ret := _mock.Called(ctx, vgName)

	if len(ret) == 0 {
		panic("no return value specified for AddTagToVG")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, vgName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLVM_AddTagToVG_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTagToVG'
type MockLVM_AddTagToVG_Call struct {
	*mock.Call
}

// AddTagToVG is a helper method to define mock.On call
//   - ctx context.Context
//   - vgName string
func (_e *MockLVM_Expecter) AddTagToVG(ctx interface{}, vgName interface{}) *MockLVM_AddTagToVG_Call {
	return &MockLVM_AddTagToVG_Call{Call: _e.mock.On("AddTagToVG", ctx, vgName)}
}

func (_c *MockLVM_AddTagToVG_Call) Run(run func(ctx context.Context, vgName string)) *MockLVM_AddTagToVG_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLVM_AddTagToVG_Call) Return(err error) *MockLVM_AddTagToVG_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLVM_AddTagToVG_Call) RunAndReturn(run func(ctx context.Context, vgName string) error) *MockLVM_AddTagToVG_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLV provides a mock function for the type MockLVM
func (_mock *MockLVM) CreateLV(ctx context.Context, lvName string, vgName string, sizePercent int, chunkSizeBytes int64, metadataSizeBytes int64) error {
	ret := _mock.Called(ctx, lvName, vgName, sizePercent, chunkSizeBytes, metadataSizeBytes)

	if len(ret) == 0 {
		panic("no return value specified for CreateLV")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, int64, int64) error); ok {
		r0 = returnFunc(ctx, lvName, vgName, sizePercent, chunkSizeBytes, metadataSizeBytes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLVM_CreateLV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLV'
type MockLVM_CreateLV_Call struct {
	*mock.Call
}

// CreateLV is a helper method to define mock.On call
//   - ctx context.Context
//   - lvName string
//   - vgName string
//   - sizePercent int
//   - chunkSizeBytes int64
//   - metadataSizeBytes int64
func (_e *MockLVM_Expecter) CreateLV(ctx interface{}, lvName interface{}, vgName interface{}, sizePercent interface{}, chunkSizeBytes interface{}, metadataSizeBytes interface{}) *MockLVM_CreateLV_Call {
	return &MockLVM_CreateLV_Call{Call: _e.mock.On("CreateLV", ctx, lvName, vgName, sizePercent, chunkSizeBytes, metadataSizeBytes)}
}

func (_c *MockLVM_CreateLV_Call) Run(run func(ctx context.Context, lvName string, vgName string, sizePercent int, chunkSizeBytes int64, metadataSizeBytes int64)) *MockLVM_CreateLV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 int64
		if args[5] != nil {
			arg5 = args[5].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockLVM_CreateLV_Call) Return(err error) *MockLVM_CreateLV_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLVM_CreateLV_Call) RunAndReturn(run func(ctx context.Context, lvName string, vgName string, sizePercent int, chunkSizeBytes int64, metadataSizeBytes int64) error) *MockLVM_CreateLV_Call {
	_c.Call.Return(run)
	return _c
}

// CreateVG provides a mock function for the type MockLVM
func (_mock *MockLVM) CreateVG(ctx context.Context, vg lvm.VolumeGroup, isWiped bool) error {
	ret := _mock.Called(ctx, vg, isWiped)

	if len(ret) == 0 {
		panic("no return value specified for CreateVG")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, lvm.VolumeGroup, bool) error); ok {
		r0 = returnFunc(ctx, vg, isWiped)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLVM_CreateVG_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVG'
type MockLVM_CreateVG_Call struct {
	*mock.Call
}

// CreateVG is a helper method to define mock.On call
//   - ctx context.Context
//   - vg lvm.VolumeGroup
//   - isWiped bool
func (_e *MockLVM_Expecter) CreateVG(ctx interface{}, vg interface{}, isWiped interface{}) *MockLVM_CreateVG_Call {
	return &MockLVM_CreateVG_Call{Call: _e.mock.On("CreateVG", ctx, vg, isWiped)}
}

func (_c *MockLVM_CreateVG_Call) Run(run func(ctx context.Context, vg lvm.VolumeGroup, isWiped bool)) *MockLVM_CreateVG_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 lvm.VolumeGroup
		if args[1] != nil {
			arg1 = args[1].(lvm.VolumeGroup)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLVM_CreateVG_Call) Return(err error) *MockLVM_CreateVG_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLVM_CreateVG_Call) RunAndReturn(run func(ctx context.Context, vg lvm.VolumeGroup, isWiped bool) error) *MockLVM_CreateVG_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLV provides a mock function for the type MockLVM
func (_mock *MockLVM) DeleteLV(ctx context.Context, lvName string, vgName string) error {
	ret := _mock.Called(ctx, lvName, vgName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLV")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, lvName, vgName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLVM_DeleteLV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLV'
type MockLVM_DeleteLV_Call struct {
	*mock.Call
}

// DeleteLV is a helper method to define mock.On call
//   - ctx context.Context
//   - lvName string
//   - vgName string
func (_e *MockLVM_Expecter) DeleteLV(ctx interface{}, lvName interface{}, vgName interface{}) *MockLVM_DeleteLV_Call {
	return &MockLVM_DeleteLV_Call{Call: _e.mock.On("DeleteLV", ctx, lvName, vgName)}
}

func (_c *MockLVM_DeleteLV_Call) Run(run func(ctx context.Context, lvName string, vgName string)) *MockLVM_DeleteLV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLVM_DeleteLV_Call) Return(err error) *MockLVM_DeleteLV_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLVM_DeleteLV_Call) RunAndReturn(run func(ctx context.Context, lvName string, vgName string) error) *MockLVM_DeleteLV_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteVG provides a mock function for the type MockLVM
func (_mock *MockLVM) DeleteVG(ctx context.Context, vg lvm.VolumeGroup) error {
	ret := _mock.Called(ctx, vg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVG")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, lvm.VolumeGroup) error); ok {
		r0 = returnFunc(ctx, vg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLVM_DeleteVG_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVG'
type MockLVM_DeleteVG_Call struct {
	*mock.Call
}

// DeleteVG is a helper method to define mock.On call
//   - ctx context.Context
//   - vg lvm.VolumeGroup
func (_e *MockLVM_Expecter) DeleteVG(ctx interface{}, vg interface{}) *MockLVM_DeleteVG_Call {
	return &MockLVM_DeleteVG_Call{Call: _e.mock.On("DeleteVG", ctx, vg)}
}

func (_c *MockLVM_DeleteVG_Call) Run(run func(ctx context.Context, vg lvm.VolumeGroup)) *MockLVM_DeleteVG_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 lvm.VolumeGroup
		if args[1] != nil {
			arg1 = args[1].(lvm.VolumeGroup)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLVM_DeleteVG_Call) Return(err error) *MockLVM_DeleteVG_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLVM_DeleteVG_Call) RunAndReturn(run func(ctx context.Context, vg lvm.VolumeGroup) error) *MockLVM_DeleteVG_Call {
	_c.Call.Return(run)
	return _c
}

// ExtendLV provides a mock function for the type MockLVM
func (_mock *MockLVM) ExtendLV(ctx context.Context, lvName string, vgName string, sizePercent int) error {
	ret := _mock.Called(ctx, lvName, vgName, sizePercent)

	if len(ret) == 0 {
		panic("no return value specified for ExtendLV")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) error); ok {
		r0 = returnFunc(ctx, lvName, vgName, sizePercent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLVM_ExtendLV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtendLV'
type MockLVM_ExtendLV_Call struct {
	*mock.Call
}

// ExtendLV is a helper method to define mock.On call
//   - ctx context.Context
//   - lvName string
//   - vgName string
//   - sizePercent int
func (_e *MockLVM_Expecter) ExtendLV(ctx interface{}, lvName interface{}, vgName interface{}, sizePercent interface{}) *MockLVM_ExtendLV_Call {
	return &MockLVM_ExtendLV_Call{Call: _e.mock.On("ExtendLV", ctx, lvName, vgName, sizePercent)}
}

func (_c *MockLVM_ExtendLV_Call) Run(run func(ctx context.Context, lvName string, vgName string, sizePercent int)) *MockLVM_ExtendLV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockLVM_ExtendLV_Call) Return(err error) *MockLVM_ExtendLV_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLVM_ExtendLV_Call) RunAndReturn(run func(ctx context.Context, lvName string, vgName string, sizePercent int) error) *MockLVM_ExtendLV_Call {
	_c.Call.Return(run)
	return _c
}

// ExtendThinPoolMetadata provides a mock function for the type MockLVM
func (_mock *MockLVM) ExtendThinPoolMetadata(ctx context.Context, lvName string, vgName string, metadataSizeBytes int64) error {
	ret := _mock.Called(ctx, lvName, vgName, metadataSizeBytes)

	if len(ret) == 0 {
		panic("no return value specified for ExtendThinPoolMetadata")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) error); ok {
		r0 = returnFunc(ctx, lvName, vgName, metadataSizeBytes)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLVM_ExtendThinPoolMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtendThinPoolMetadata'
type MockLVM_ExtendThinPoolMetadata_Call struct {
	*mock.Call
}

// ExtendThinPoolMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - lvName string
//   - vgName string
//   - metadataSizeBytes int64
func (_e *MockLVM_Expecter) ExtendThinPoolMetadata(ctx interface{}, lvName interface{}, vgName interface{}, metadataSizeBytes interface{}) *MockLVM_ExtendThinPoolMetadata_Call {
	return &MockLVM_ExtendThinPoolMetadata_Call{Call: _e.mock.On("ExtendThinPoolMetadata", ctx, lvName, vgName, metadataSizeBytes)}
}

func (_c *MockLVM_ExtendThinPoolMetadata_Call) Run(run func(ctx context.Context, lvName string, vgName string, metadataSizeBytes int64)) *MockLVM_ExtendThinPoolMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockLVM_ExtendThinPoolMetadata_Call) Return(err error) *MockLVM_ExtendThinPoolMetadata_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLVM_ExtendThinPoolMetadata_Call) RunAndReturn(run func(ctx context.Context, lvName string, vgName string, metadataSizeBytes int64) error) *MockLVM_ExtendThinPoolMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// ExtendVG provides a mock function for the type MockLVM
func (_mock *MockLVM) ExtendVG(ctx context.Context, vg lvm.VolumeGroup, pvs []string) (lvm.VolumeGroup, error) {
	ret := _mock.Called(ctx, vg, pvs)

	if len(ret) == 0 {
		panic("no return value specified for ExtendVG")
	}

	var r0 lvm.VolumeGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, lvm.VolumeGroup, []string) (lvm.VolumeGroup, error)); ok {
		return returnFunc(ctx, vg, pvs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, lvm.VolumeGroup, []string) lvm.VolumeGroup); ok {
		r0 = returnFunc(ctx, vg, pvs)
	} else {
		r0 = ret.Get(0).(lvm.VolumeGroup)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, lvm.VolumeGroup, []string) error); ok {
		r1 = returnFunc(ctx, vg, pvs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLVM_ExtendVG_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtendVG'
type MockLVM_ExtendVG_Call struct {
	*mock.Call
}

// ExtendVG is a helper method to define mock.On call
//   - ctx context.Context
//   - vg lvm.VolumeGroup
//   - pvs []string
func (_e *MockLVM_Expecter) ExtendVG(ctx interface{}, vg interface{}, pvs interface{}) *MockLVM_ExtendVG_Call {
	return &MockLVM_ExtendVG_Call{Call: _e.mock.On("ExtendVG", ctx, vg, pvs)}
}

func (_c *MockLVM_ExtendVG_Call) Run(run func(ctx context.Context, vg lvm.VolumeGroup, pvs []string)) *MockLVM_ExtendVG_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 lvm.VolumeGroup
		if args[1] != nil {
			arg1 = args[1].(lvm.VolumeGroup)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLVM_ExtendVG_Call) Return(volumeGroup lvm.VolumeGroup, err error) *MockLVM_ExtendVG_Call {
	_c.Call.Return(volumeGroup, err)
	return _c
}

func (_c *MockLVM_ExtendVG_Call) RunAndReturn(run func(ctx context.Context, vg lvm.VolumeGroup, pvs []string) (lvm.VolumeGroup, error)) *MockLVM_ExtendVG_Call {
	_c.Call.Return(run)
	return _c
}

// GetVG provides a mock function for the type MockLVM
func (_mock *MockLVM) GetVG(ctx context.Context, name string) (lvm.VolumeGroup, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetVG")
	}

	var r0 lvm.VolumeGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (lvm.VolumeGroup, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) lvm.VolumeGroup); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(lvm.VolumeGroup)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLVM_GetVG_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVG'
type MockLVM_GetVG_Call struct {
	*mock.Call
}

// GetVG is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockLVM_Expecter) GetVG(ctx interface{}, name interface{}) *MockLVM_GetVG_Call {
	return &MockLVM_GetVG_Call{Call: _e.mock.On("GetVG", ctx, name)}
}

func (_c *MockLVM_GetVG_Call) Run(run func(ctx context.Context, name string)) *MockLVM_GetVG_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLVM_GetVG_Call) Return(volumeGroup lvm.VolumeGroup, err error) *MockLVM_GetVG_Call {
	_c.Call.Return(volumeGroup, err)
	return _c
}

func (_c *MockLVM_GetVG_Call) RunAndReturn(run func(ctx context.Context, name string) (lvm.VolumeGroup, error)) *MockLVM_GetVG_Call {
	_c.Call.Return(run)
	return _c
}

// LVExists provides a mock function for the type MockLVM
func (_mock *MockLVM) LVExists(ctx context.Context, lvName string, vgName string) (bool, error) {
	ret := _mock.Called(ctx, lvName, vgName)

	if len(ret) == 0 {
		panic("no return value specified for LVExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, lvName, vgName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, lvName, vgName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, lvName, vgName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLVM_LVExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LVExists'
type MockLVM_LVExists_Call struct {
	*mock.Call
}

// LVExists is a helper method to define mock.On call
//   - ctx context.Context
//   - lvName string
//   - vgName string
func (_e *MockLVM_Expecter) LVExists(ctx interface{}, lvName interface{}, vgName interface{}) *MockLVM_LVExists_Call {
	return &MockLVM_LVExists_Call{Call: _e.mock.On("LVExists", ctx, lvName, vgName)}
}

func (_c *MockLVM_LVExists_Call) Run(run func(ctx context.Context, lvName string, vgName string)) *MockLVM_LVExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLVM_LVExists_Call) Return(b bool, err error) *MockLVM_LVExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockLVM_LVExists_Call) RunAndReturn(run func(ctx context.Context, lvName string, vgName string) (bool, error)) *MockLVM_LVExists_Call {
	_c.Call.Return(run)
	return _c
}

// ListLVs provides a mock function for the type MockLVM
func (_mock *MockLVM) ListLVs(ctx context.Context, vgName string) (*lvm.LVReport, error) {
	ret := _mock.Called(ctx, vgName)

	if len(ret) == 0 {
		panic("no return value specified for ListLVs")
	}

	var r0 *lvm.LVReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*lvm.LVReport, error)); ok {
		return returnFunc(ctx, vgName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *lvm.LVReport); ok {
		r0 = returnFunc(ctx, vgName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lvm.LVReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, vgName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLVM_ListLVs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLVs'
type MockLVM_ListLVs_Call struct {
	*mock.Call
}

// ListLVs is a helper method to define mock.On call
//   - ctx context.Context
//   - vgName string
func (_e *MockLVM_Expecter) ListLVs(ctx interface{}, vgName interface{}) *MockLVM_ListLVs_Call {
	return &MockLVM_ListLVs_Call{Call: _e.mock.On("ListLVs", ctx, vgName)}
}

func (_c *MockLVM_ListLVs_Call) Run(run func(ctx context.Context, vgName string)) *MockLVM_ListLVs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLVM_ListLVs_Call) Return(lVReport *lvm.LVReport, err error) *MockLVM_ListLVs_Call {
	_c.Call.Return(lVReport, err)
	return _c
}

func (_c *MockLVM_ListLVs_Call) RunAndReturn(run func(ctx context.Context, vgName string) (*lvm.LVReport, error)) *MockLVM_ListLVs_Call {
	_c.Call.Return(run)
	return _c
}

// ListLVsByName provides a mock function for the type MockLVM
func (_mock *MockLVM) ListLVsByName(ctx context.Context, vgName string) ([]string, error) {
	ret := _mock.Called(ctx, vgName)

	if len(ret) == 0 {
		panic("no return value specified for ListLVsByName")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, vgName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, vgName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, vgName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLVM_ListLVsByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLVsByName'
type MockLVM_ListLVsByName_Call struct {
	*mock.Call
}

// ListLVsByName is a helper method to define mock.On call
//   - ctx context.Context
//   - vgName string
func (_e *MockLVM_Expecter) ListLVsByName(ctx interface{}, vgName interface{}) *MockLVM_ListLVsByName_Call {
	return &MockLVM_ListLVsByName_Call{Call: _e.mock.On("ListLVsByName", ctx, vgName)}
}

func (_c *MockLVM_ListLVsByName_Call) Run(run func(ctx context.Context, vgName string)) *MockLVM_ListLVsByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLVM_ListLVsByName_Call) Return(strings []string, err error) *MockLVM_ListLVsByName_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockLVM_ListLVsByName_Call) RunAndReturn(run func(ctx context.Context, vgName string) ([]string, error)) *MockLVM_ListLVsByName_Call {
	_c.Call.Return(run)
	return _c
}

// ListPVs provides a mock function for the type MockLVM
func (_mock *MockLVM) ListPVs(ctx context.Context, vgName string) ([]lvm.PhysicalVolume, error) {
	ret := _mock.Called(ctx, vgName)

	if len(ret) == 0 {
		panic("no return value specified for ListPVs")
	}

	var r0 []lvm.PhysicalVolume
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]lvm.PhysicalVolume, error)); ok {
		return returnFunc(ctx, vgName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []lvm.PhysicalVolume); ok {
		r0 = returnFunc(ctx, vgName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]lvm.PhysicalVolume)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, vgName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLVM_ListPVs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPVs'
type MockLVM_ListPVs_Call struct {
	*mock.Call
}

// ListPVs is a helper method to define mock.On call
//   - ctx context.Context
//   - vgName string
func (_e *MockLVM_Expecter) ListPVs(ctx interface{}, vgName interface{}) *MockLVM_ListPVs_Call {
	return &MockLVM_ListPVs_Call{Call: _e.mock.On("ListPVs", ctx, vgName)}
}

func (_c *MockLVM_ListPVs_Call) Run(run func(ctx context.Context, vgName string)) *MockLVM_ListPVs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLVM_ListPVs_Call) Return(physicalVolumes []lvm.PhysicalVolume, err error) *MockLVM_ListPVs_Call {
	_c.Call.Return(physicalVolumes, err)
	return _c
}

func (_c *MockLVM_ListPVs_Call) RunAndReturn(run func(ctx context.Context, vgName string) ([]lvm.PhysicalVolume, error)) *MockLVM_ListPVs_Call {
	_c.Call.Return(run)
	return _c
}

// ListVGs provides a mock function for the type MockLVM
func (_mock *MockLVM) ListVGs(ctx context.Context, taggedByLVMS bool) ([]lvm.VolumeGroup, error) {
	ret := _mock.Called(ctx, taggedByLVMS)

	if len(ret) == 0 {
		panic("no return value specified for ListVGs")
	}

	var r0 []lvm.VolumeGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) ([]lvm.VolumeGroup, error)); ok {
		return returnFunc(ctx, taggedByLVMS)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) []lvm.VolumeGroup); ok {
		r0 = returnFunc(ctx, taggedByLVMS)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]lvm.VolumeGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = returnFunc(ctx, taggedByLVMS)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLVM_ListVGs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVGs'
type MockLVM_ListVGs_Call struct {
	*mock.Call
}

// ListVGs is a helper method to define mock.On call
//   - ctx context.Context
//   - taggedByLVMS bool
func (_e *MockLVM_Expecter) ListVGs(ctx interface{}, taggedByLVMS interface{}) *MockLVM_ListVGs_Call {
	return &MockLVM_ListVGs_Call{Call: _e.mock.On("ListVGs", ctx, taggedByLVMS)}
}

func (_c *MockLVM_ListVGs_Call) Run(run func(ctx context.Context, taggedByLVMS bool)) *MockLVM_ListVGs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLVM_ListVGs_Call) Return(volumeGroups []lvm.VolumeGroup, err error) *MockLVM_ListVGs_Call {
	_c.Call.Return(volumeGroups, err)
	return _c
}

func (_c *MockLVM_ListVGs_Call) RunAndReturn(run func(ctx context.Context, taggedByLVMS bool) ([]lvm.VolumeGroup, error)) *MockLVM_ListVGs_Call {
	_c.Call.Return(run)
	return _c
}

// ReduceVG provides a mock function for the type MockLVM
func (_mock *MockLVM) ReduceVG(ctx context.Context, vgName string, devices string) error {
	ret := _mock.Called(ctx, vgName, devices)

	if len(ret) == 0 {
		panic("no return value specified for ReduceVG")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, vgName, devices)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLVM_ReduceVG_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReduceVG'
type MockLVM_ReduceVG_Call struct {
	*mock.Call
}

// ReduceVG is a helper method to define mock.On call
//   - ctx context.Context
//   - vgName string
//   - devices string
func (_e *MockLVM_Expecter) ReduceVG(ctx interface{}, vgName interface{}, devices interface{}) *MockLVM_ReduceVG_Call {
	return &MockLVM_ReduceVG_Call{Call: _e.mock.On("ReduceVG", ctx, vgName, devices)}
}

func (_c *MockLVM_ReduceVG_Call) Run(run func(ctx context.Context, vgName string, devices string)) *MockLVM_ReduceVG_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLVM_ReduceVG_Call) Return(err error) *MockLVM_ReduceVG_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLVM_ReduceVG_Call) RunAndReturn(run func(ctx context.Context, vgName string, devices string) error) *MockLVM_ReduceVG_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePV provides a mock function for the type MockLVM
func (_mock *MockLVM) RemovePV(ctx context.Context, devicePath string) error {
	ret := _mock.Called(ctx, devicePath)

	if len(ret) == 0 {
		panic("no return value specified for RemovePV")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, devicePath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLVM_RemovePV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePV'
type MockLVM_RemovePV_Call struct {
	*mock.Call
}

// RemovePV is a helper method to define mock.On call
//   - ctx context.Context
//   - devicePath string
func (_e *MockLVM_Expecter) RemovePV(ctx interface{}, devicePath interface{}) *MockLVM_RemovePV_Call {
	return &MockLVM_RemovePV_Call{Call: _e.mock.On("RemovePV", ctx, devicePath)}
}

func (_c *MockLVM_RemovePV_Call) Run(run func(ctx context.Context, devicePath string)) *MockLVM_RemovePV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLVM_RemovePV_Call) Return(err error) *MockLVM_RemovePV_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLVM_RemovePV_Call) RunAndReturn(run func(ctx context.Context, devicePath string) error) *MockLVM_RemovePV_Call {
	_c.Call.Return(run)
	return _c
}
